apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" . }}-deployment
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "chart.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "chart.fullname" . }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        name: {{ template "chart.fullname" . }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.aspnetcoreEnvironment | default "Production" }}
        volumeMounts:
          {{- if .Values.deployment.appsettings }}
          - name: appsettings-volume
            mountPath: /app/appsettings.Active.json
            subPath: appsettings.Active.json
          {{- end }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
      - name: {{ template "chart.fullname" . }}-docker-secret
      volumes:
      {{- if .Values.deployment.appsettings }}
      - name: appsettings-volume
        configMap:
          name: {{ template "chart.fullname" . }}-env
          items:
          - key: appsettings.Active.json 
            path: appsettings.Active.json
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}