{{ if .Values.deploySecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chart.fullname" . }}-secret
type: Opaque
data:
  ConnectionStrings__DefaultConnection: {{ required "ConnectionStrings.DefaultConnection must be defined!" .Values.ConnectionStrings.DefaultConnection | b64enc | quote }}
{{ end }}
