apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "auth.fullname" . }}-env
data:
  {{- if .Values.deployment.appsettings }}
  appsettings.Active.json: |-
{{ toJson .Values.deployment.appsettings | indent 4 }}
  {{- end }}