apiVersion: v1
kind: Service
metadata:
  name: {{ template "auth.fullname" . }}-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ template "auth.fullname" . }}
  type: ClusterIP